import {
  checkForACookie,
  checkForAWSCCC,
  checkForBorgerCookie,
  checkForCC,
  checkForCmplz,
  checkForCookieBot,
  checkForCookieConsent,
  checkForCookieScript,
  checkForCookieYes,
  checkForDelve,
  checkForDidomi,
  checkForDrCookie,
  checkForEbayGDPR,
  checkForEzoic,
  checkForFides,
  checkForFreeChoice,
  checkForGeneric,
  checkForGitBookCookies,
  checkForIubenda,
  checkForNikeCookie,
  checkForOneTrust,
  checkForOneUptimeCookie,
  checkForPopupBox,
  checkForPornhubCookie,
  checkForQuantcast,
  checkForSourcepoint,
  checkForSquarespaceCookie,
  checkForTermly,
  checkForTranscend,
  checkForTrustArc,
  checkForTrustee,
  checkForUCGDPR,
  checkForUserCentrics,
  checkForWebToffee,
  checkForWixCookieBanner,
  checkForWorkableCookie,
  checkForXCookieBanner,
  checkForXHCookiesModal,
  checkForYahooGUCE,
  checkForCookieBar,
  checkForUniConsent,
} from './checks';
import {
  closeOrRejectACookie,
  closeOrRejectCC,
  closeOrRejectCmplz,
  closeOrRejectCookieYes,
  closeOrRejectDelve,
  closeOrRejectDidomi,
  closeOrRejectDrCookie,
  closeOrRejectEbayGDPR,
  closeOrRejectFides,
  closeOrRejectFreeChoice,
  closeOrRejectGeneric,
  closeOrRejectIubenda,
  closeOrRejectNikeCookie,
  closeOrRejectOneTrust,
  closeOrRejectPornhubCookie,
  closeOrRejectQuantcast,
  closeOrRejectSquarespaceCookie,
  closeOrRejectTrustArc,
  closeOrRejectTrustee,
  closeOrRejectWixCookieBanner,
  closeOrRejectXCookieBanner,
  closeOrRejectYahooGUCE,
  closeOrRejectCookieBar,
  closeOrRejectBorgerCookie,
  closeOrRejectCookieConsent,
  closeOrRejectEzoic,
  closeOrRejectGitBookCookies,
  closeOrRejectOneUptimeCookie,
  closeOrRejectPopupBox,
  closeOrRejectUniConsent,
  closeOrRejectWebToffee,
  closeOrRejectWorkableCookie,
  closeOrRejectXHCookiesModal,
  closeSourcepoint,
  closeTranscend,
  rejectAWSCCC,
  rejectCookieBot,
  rejectCookieScript,
  rejectOrCloseUCGDPR,
  rejectTermly,
  rejectUserCentrics,
} from './rejectFlows';
import { CookiePopupCheck } from './types';

export const commonCookiePopupChecks: CookiePopupCheck[] = [
  {
    name: 'onetrust',
    check: checkForOneTrust,
    rejectOrClose: closeOrRejectOneTrust,
    successful: false,
  },
  {
    name: 'transcend',
    check: checkForTranscend,
    rejectOrClose: closeTranscend,
    successful: false,
  },
  {
    name: 'cookieyes',
    check: checkForCookieYes,
    rejectOrClose: closeOrRejectCookieYes,
    successful: false,
  },
  {
    name: 'cookiebot',
    check: checkForCookieBot,
    rejectOrClose: rejectCookieBot,
    successful: false,
  },
  {
    name: 'usercentrics',
    check: checkForUserCentrics,
    rejectOrClose: rejectUserCentrics,
    successful: false,
  },
  {
    name: 'didomi',
    check: checkForDidomi,
    rejectOrClose: closeOrRejectDidomi,
    successful: false,
  },
  {
    name: 'trustarc',
    check: checkForTrustArc,
    rejectOrClose: closeOrRejectTrustArc,
    successful: false,
  },
  {
    name: 'dr',
    check: checkForDrCookie,
    rejectOrClose: closeOrRejectDrCookie,
    successful: false,
  },
  {
    name: 'uc-gdpr',
    check: checkForUCGDPR,
    rejectOrClose: rejectOrCloseUCGDPR,
    successful: false,
  },
  {
    name: 'cc',
    check: checkForCC,
    rejectOrClose: closeOrRejectCC,
    successful: false,
  },
  {
    name: 'generic',
    check: checkForGeneric,
    rejectOrClose: closeOrRejectGeneric,
    successful: false,
  },
  {
    name: 'trustee',
    check: checkForTrustee,
    rejectOrClose: closeOrRejectTrustee,
    successful: false,
  },
  {
    name: 'cmplz',
    check: checkForCmplz,
    rejectOrClose: closeOrRejectCmplz,
    successful: false,
  },
  {
    name: 'acookie',
    check: checkForACookie,
    rejectOrClose: closeOrRejectACookie,
    successful: false,
  },
  {
    name: 'sourcepoint',
    check: checkForSourcepoint,
    rejectOrClose: closeSourcepoint,
    successful: false,
  },
  {
    name: 'quantcast',
    check: checkForQuantcast,
    rejectOrClose: closeOrRejectQuantcast,
    successful: false,
  },
  {
    name: 'iubenda',
    check: checkForIubenda,
    rejectOrClose: closeOrRejectIubenda,
    successful: false,
  },
  {
    name: 'fides',
    check: checkForFides,
    rejectOrClose: closeOrRejectFides,
    successful: false,
  },
  {
    name: 'delve',
    check: checkForDelve,
    rejectOrClose: closeOrRejectDelve,
    successful: false,
  },
  {
    name: 'nike-cookie',
    check: checkForNikeCookie,
    rejectOrClose: closeOrRejectNikeCookie,
    successful: false,
  },
  {
    name: 'ebay-gdpr',
    check: checkForEbayGDPR,
    rejectOrClose: closeOrRejectEbayGDPR,
    successful: false,
  },
  {
    name: 'freechoice',
    check: checkForFreeChoice,
    rejectOrClose: closeOrRejectFreeChoice,
    successful: false,
  },
  {
    name: 'wix-cookie-banner',
    check: checkForWixCookieBanner,
    rejectOrClose: closeOrRejectWixCookieBanner,
    successful: false,
  },
  {
    name: 'yahoo-guce',
    check: checkForYahooGUCE,
    rejectOrClose: closeOrRejectYahooGUCE,
    successful: false,
  },
  {
    name: 'x-cookie-banner',
    check: checkForXCookieBanner,
    rejectOrClose: closeOrRejectXCookieBanner,
    successful: false,
  },
  {
    name: 'cookiebar',
    check: checkForCookieBar,
    rejectOrClose: closeOrRejectCookieBar,
    successful: false,
  },
  {
    name: 'uniconsent',
    check: checkForUniConsent,
    rejectOrClose: closeOrRejectUniConsent,
    successful: false,
  },
  {
    name: 'popup-box',
    check: checkForPopupBox,
    rejectOrClose: closeOrRejectPopupBox,
    successful: false,
  },
  {
    name: 'xh-cookies',
    check: checkForXHCookiesModal,
    rejectOrClose: closeOrRejectXHCookiesModal,
    successful: false,
  },
  {
    name: 'cookiescript',
    check: checkForCookieScript,
    rejectOrClose: rejectCookieScript,
    successful: false,
  },
  {
    name: 'awsccc',
    check: checkForAWSCCC,
    rejectOrClose: rejectAWSCCC,
    successful: false,
  },
  {
    name: 'squarespace-cookie',
    check: checkForSquarespaceCookie,
    rejectOrClose: closeOrRejectSquarespaceCookie,
    successful: false,
  },
  {
    name: 'termly',
    check: checkForTermly,
    rejectOrClose: rejectTermly,
    successful: false,
  },
  {
    name: 'pornhub-cookie',
    check: checkForPornhubCookie,
    rejectOrClose: closeOrRejectPornhubCookie,
    successful: false,
  },
  {
    name: 'cookieconsent',
    check: checkForCookieConsent,
    rejectOrClose: closeOrRejectCookieConsent,
    successful: false,
  },
  {
    name: 'workable',
    check: checkForWorkableCookie,
    rejectOrClose: closeOrRejectWorkableCookie,
    successful: false,
  },
  {
    name: 'webtoffee',
    check: checkForWebToffee,
    rejectOrClose: closeOrRejectWebToffee,
    successful: false,
  },
  {
    name: 'borger-cookie',
    check: checkForBorgerCookie,
    rejectOrClose: closeOrRejectBorgerCookie,
    successful: false,
  },
  {
    name: 'ezoic',
    check: checkForEzoic,
    rejectOrClose: closeOrRejectEzoic,
    successful: false,
  },
  {
    name: 'gitbook-cookies',
    check: checkForGitBookCookies,
    rejectOrClose: closeOrRejectGitBookCookies,
    successful: false,
  },
  {
    name: 'oneuptime-cookie',
    check: checkForOneUptimeCookie,
    rejectOrClose: closeOrRejectOneUptimeCookie,
    successful: false,
  },
];
