import {
  checkForACookie,
  checkForCC,
  checkForCmplz,
  checkForCookieBot,
  checkForCookieYes,
  checkForDidomi,
  checkForDrCookie,
  checkForGeneric,
  checkForIubenda,
  checkForOneTrust,
  checkForQuantcast,
  checkForSourcepoint,
  checkForTranscend,
  checkForTrustArc,
  checkForTrustee,
  checkForUCGDPR,
  checkForUserCentrics,
} from './checks';
import {
  closeOrRejectACookie,
  closeOrRejectCC,
  closeOrRejectCmplz,
  closeOrRejectCookieYes,
  closeOrRejectDidomi,
  closeOrRejectDrCookie,
  closeOrRejectGeneric,
  closeOrRejectIubenda,
  closeOrRejectOneTrust,
  closeOrRejectQuantcast,
  closeOrRejectTrustArc,
  closeOrRejectTrustee,
  closeSourcepoint,
  closeTranscend,
  rejectCookieBot,
  rejectOrCloseUCGDPR,
  rejectUserCentrics,
} from './rejectFlows';
import { CookiePopupCheck } from './types';

export const commonCookiePopupChecks: CookiePopupCheck[] = [
  {
    name: 'onetrust',
    check: checkForOneTrust,
    rejectOrClose: closeOrRejectOneTrust,
    successful: false,
  },
  {
    name: 'transcend',
    check: checkForTranscend,
    rejectOrClose: closeTranscend,
    successful: false,
  },
  {
    name: 'cookieyes',
    check: checkForCookieYes,
    rejectOrClose: closeOrRejectCookieYes,
    successful: false,
  },
  {
    name: 'cookiebot',
    check: checkForCookieBot,
    rejectOrClose: rejectCookieBot,
    successful: false,
  },
  {
    name: 'usercentrics',
    check: checkForUserCentrics,
    rejectOrClose: rejectUserCentrics,
    successful: false,
  },
  {
    name: 'didomi',
    check: checkForDidomi,
    rejectOrClose: closeOrRejectDidomi,
    successful: false,
  },
  {
    name: 'trustarc',
    check: checkForTrustArc,
    rejectOrClose: closeOrRejectTrustArc,
    successful: false,
  },
  {
    name: 'dr',
    check: checkForDrCookie,
    rejectOrClose: closeOrRejectDrCookie,
    successful: false,
  },
  {
    name: 'uc-gdpr',
    check: checkForUCGDPR,
    rejectOrClose: rejectOrCloseUCGDPR,
    successful: false,
  },
  {
    name: 'cc',
    check: checkForCC,
    rejectOrClose: closeOrRejectCC,
    successful: false,
  },
  {
    name: 'generic',
    check: checkForGeneric,
    rejectOrClose: closeOrRejectGeneric,
    successful: false,
  },
  {
    name: 'trustee',
    check: checkForTrustee,
    rejectOrClose: closeOrRejectTrustee,
    successful: false,
  },
  {
    name: 'cmplz',
    check: checkForCmplz,
    rejectOrClose: closeOrRejectCmplz,
    successful: false,
  },
  {
    name: 'acookie',
    check: checkForACookie,
    rejectOrClose: closeOrRejectACookie,
    successful: false,
  },
  {
    name: 'sourcepoint',
    check: checkForSourcepoint,
    rejectOrClose: closeSourcepoint,
    successful: false,
  },
  {
    name: 'quantcast',
    check: checkForQuantcast,
    rejectOrClose: closeOrRejectQuantcast,
    successful: false,
  },
  {
    name: 'iubenda',
    check: checkForIubenda,
    rejectOrClose: closeOrRejectIubenda,
    successful: false,
  },
];
