import {
  checkForACookie,
  checkForCC,
  checkForCmplz,
  checkForCookieBot,
  checkForCookieYes,
  checkForDelve,
  checkForDidomi,
  checkForDrCookie,
  checkForEbayGDPR,
  checkForFides,
  checkForFreeChoice,
  checkForGeneric,
  checkForIubenda,
  checkForNikeCookie,
  checkForOneTrust,
  checkForQuantcast,
  checkForSourcepoint,
  checkForTranscend,
  checkForTrustArc,
  checkForTrustee,
  checkForUCGDPR,
  checkForUserCentrics,
  checkForWixCookieBanner,
  checkForXCookieBanner,
  checkForYahooGUCE,
} from './checks';
import {
  closeOrRejectACookie,
  closeOrRejectCC,
  closeOrRejectCmplz,
  closeOrRejectCookieYes,
  closeOrRejectDelve,
  closeOrRejectDidomi,
  closeOrRejectDrCookie,
  closeOrRejectEbayGDPR,
  closeOrRejectFides,
  closeOrRejectFreeChoice,
  closeOrRejectGeneric,
  closeOrRejectIubenda,
  closeOrRejectNikeCookie,
  closeOrRejectOneTrust,
  closeOrRejectQuantcast,
  closeOrRejectTrustArc,
  closeOrRejectTrustee,
  closeOrRejectWixCookieBanner,
  closeOrRejectXCookieBanner,
  closeOrRejectYahooGUCE,
  closeSourcepoint,
  closeTranscend,
  rejectCookieBot,
  rejectOrCloseUCGDPR,
  rejectUserCentrics,
} from './rejectFlows';
import { CookiePopupCheck } from './types';

export const commonCookiePopupChecks: CookiePopupCheck[] = [
  {
    name: 'onetrust',
    check: checkForOneTrust,
    rejectOrClose: closeOrRejectOneTrust,
    successful: false,
  },
  {
    name: 'transcend',
    check: checkForTranscend,
    rejectOrClose: closeTranscend,
    successful: false,
  },
  {
    name: 'cookieyes',
    check: checkForCookieYes,
    rejectOrClose: closeOrRejectCookieYes,
    successful: false,
  },
  {
    name: 'cookiebot',
    check: checkForCookieBot,
    rejectOrClose: rejectCookieBot,
    successful: false,
  },
  {
    name: 'usercentrics',
    check: checkForUserCentrics,
    rejectOrClose: rejectUserCentrics,
    successful: false,
  },
  {
    name: 'didomi',
    check: checkForDidomi,
    rejectOrClose: closeOrRejectDidomi,
    successful: false,
  },
  {
    name: 'trustarc',
    check: checkForTrustArc,
    rejectOrClose: closeOrRejectTrustArc,
    successful: false,
  },
  {
    name: 'dr',
    check: checkForDrCookie,
    rejectOrClose: closeOrRejectDrCookie,
    successful: false,
  },
  {
    name: 'uc-gdpr',
    check: checkForUCGDPR,
    rejectOrClose: rejectOrCloseUCGDPR,
    successful: false,
  },
  {
    name: 'cc',
    check: checkForCC,
    rejectOrClose: closeOrRejectCC,
    successful: false,
  },
  {
    name: 'generic',
    check: checkForGeneric,
    rejectOrClose: closeOrRejectGeneric,
    successful: false,
  },
  {
    name: 'trustee',
    check: checkForTrustee,
    rejectOrClose: closeOrRejectTrustee,
    successful: false,
  },
  {
    name: 'cmplz',
    check: checkForCmplz,
    rejectOrClose: closeOrRejectCmplz,
    successful: false,
  },
  {
    name: 'acookie',
    check: checkForACookie,
    rejectOrClose: closeOrRejectACookie,
    successful: false,
  },
  {
    name: 'sourcepoint',
    check: checkForSourcepoint,
    rejectOrClose: closeSourcepoint,
    successful: false,
  },
  {
    name: 'quantcast',
    check: checkForQuantcast,
    rejectOrClose: closeOrRejectQuantcast,
    successful: false,
  },
  {
    name: 'iubenda',
    check: checkForIubenda,
    rejectOrClose: closeOrRejectIubenda,
    successful: false,
  },
  {
    name: 'fides',
    check: checkForFides,
    rejectOrClose: closeOrRejectFides,
    successful: false,
  },
  {
    name: 'delve',
    check: checkForDelve,
    rejectOrClose: closeOrRejectDelve,
    successful: false,
  },
  {
    name: 'nike-cookie',
    check: checkForNikeCookie,
    rejectOrClose: closeOrRejectNikeCookie,
    successful: false,
  },
  {
    name: 'ebay-gdpr',
    check: checkForEbayGDPR,
    rejectOrClose: closeOrRejectEbayGDPR,
    successful: false,
  },
  {
    name: 'freechoice',
    check: checkForFreeChoice,
    rejectOrClose: closeOrRejectFreeChoice,
    successful: false,
  },
  {
    name: 'wix-cookie-banner',
    check: checkForWixCookieBanner,
    rejectOrClose: closeOrRejectWixCookieBanner,
    successful: false,
  },
  {
    name: 'yahoo-guce',
    check: checkForYahooGUCE,
    rejectOrClose: closeOrRejectYahooGUCE,
    successful: false,
  },
  {
    name: 'x-cookie-banner',
    check: checkForXCookieBanner,
    rejectOrClose: closeOrRejectXCookieBanner,
    successful: false,
  },
];
